version: "3.1"

services:

    server:

        build: .

        ports:  
        - "8080:8080"

        command: ./MyFirstService


    mysqldb:

        image: mysql:5.7.32

        environment: 
            - MYSQL_ROOT_PASSWORD=1643
         
    
    
        
            
      

