version: "2.1"

services:
        # контейнер с сервером
    server:

        build: .

        ports:  
        - "8080:8080"

        command: ./MyFirstService -user=ilya -pass=1616 

        restart: always
        
        # контейнер с базой
    mysqldb:

        image: mysql:5.7.32

        environment: 
            - MYSQL_ROOT_PASSWORD=1643
            - MYSQL_USER=ilya
            - MYSQL_PASSWORD=1616
    
    
        
            
      

